lib/ex_micro_blog_web/router.ex
defmodule ExMicroBlogWeb.Router do
  use ExMicroBlogWeb, :router

  import Phoenix.LiveView.Router

  pipeline :browser do
    plug :accepts, ["html"]
    plug :fetch_session
    plug :fetch_live_flash
    plug :protect_from_forgery
    plug :put_secure_browser_headers
    plug ExMicroBlogWeb.Auth
  end

  pipeline :api do
    plug :accepts, ["json"]
  end

  scope "/", ExMicroBlogWeb do
    pipe_through :browser

    get "/", TimelineController, :index
    get "/users/:id/followers", UserController, :follower
    get "/users/:id/following", UserController, :following
    resources "/users", UserController, only: [:index, :new, :create]
    resources "/sessions", SessionController, only: [:new, :create, :delete]
    get "/:username", UserController, :username
  end
end

lib/ex_micro_blog_web/views/layout_view.ex
defmodule ExMicroBlogWeb.LayoutView do
  use ExMicroBlogWeb, :view
end

lib/ex_micro_blog_web/templates/layout/app.html.eex
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8"/>
    <meta http-equiv="X-UA-Compatible" content="IE=edge"/>
    <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
    <title>Microblog</title>
    <link rel="stylesheet" href="<%= Routes.static_path(@conn, "/css/app.css") %>"/>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
  </head>
  <body>
    <header>
      <section class="container">
        <nav role="navigation">
          <%= link "See all users", to: Routes.user_path(@conn, :index) %>
          <%= if @current_user do %>
            <span class="menu-username">
              <%= link "Following #{following_count(@current_user)}",
                to: Routes.user_path(@conn, :following, @current_user.id) %>
            </span>
            <span class="menu-username">
              <%= link "Followers #{followers_count(@current_user)}",
                to: Routes.user_path(@conn, :follower, @current_user.id) %>
            </span>
            <span class="menu-link">
              <%= link "Log out",
                to: Routes.session_path(@conn, :delete, @current_user),
                method: "delete" %>
            </span>
          <% else %>
            <%= link "Register", to: Routes.user_path(@conn, :new) %>
            <%= link "Log in", to: Routes.session_path(@conn, :new) %>
          <% end %>
        </nav>
        <h1 class="header">
          <%= link "Microblog",
            to: Routes.timeline_path(@conn, :index) %>
        </h1>
      </section>
    </header>
    <main role="main" class="container">
      <p class="alert alert-info" role="alert"><%= get_flash(@conn, :info) %></p>
      <p class="alert alert-danger" role="alert"><%= get_flash(@conn, :error) %></p>
      <%= render @view_module, @view_template, assigns %>
    </main>
    <center><a href="https://github.com/CassiusPacheco/ex_micro_blog">Check out the source code on Github</a></center>
    <br/>
    <br/>
    <%= csrf_meta_tag() %>
    <script type="text/javascript" src="<%= Routes.static_path(@conn, "/js/app.js") %>"></script>
  </body>
</html>